# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# Added at 2018-09-23 17:40:07 +0100 by ricardo:
gem "rack", "~> 2.0"
